/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.inc;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.FlowLayout;
import javax.swing.JButton;
import javax.swing.JPanel;
import view1.PnTTFCFS;
import view1.PnTTRR;
import view1.PnTTSJF;
import view1.PnTTSRT;

/**
 *
 * @author homin
 */
public class PnTop extends javax.swing.JPanel{
    /**
     * Creates new form PnTop
     */
    private JButton btRecently=null;
    private JPanel pnCenter;
    public PnTop(PnCenter pn) {
        initComponents();
       pnCenter=pn ;
       
     
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        pnTaiSan = new javax.swing.JPanel();
        btFCFS = new javax.swing.JButton();
        btSJF = new javax.swing.JButton();
        btRR = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        lbTop1 = new javax.swing.JLabel();

        setLayout(new java.awt.GridLayout(1, 3));

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setLayout(new java.awt.BorderLayout());

        pnTaiSan.setLayout(new java.awt.GridLayout(1, 3));

        btFCFS.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btFCFS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/F.png"))); // NOI18N
        btFCFS.setText("<html>First Come First Served <br />(FCFS)</html>");
        btFCFS.setBorder(null);
        btFCFS.setBorderPainted(false);
        btFCFS.setFocusPainted(false);
        btFCFS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFCFSActionPerformed(evt);
            }
        });
        pnTaiSan.add(btFCFS);

        btSJF.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btSJF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/S.png"))); // NOI18N
        btSJF.setText("<html>Shortest Job First<br />(SJF)</html>");
        btSJF.setBorder(null);
        btSJF.setBorderPainted(false);
        btSJF.setFocusPainted(false);
        btSJF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSJFActionPerformed(evt);
            }
        });
        pnTaiSan.add(btSJF);

        btRR.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btRR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/R - Copy.png"))); // NOI18N
        btRR.setText("<html>Round-robin <br />(RR) </html>");
        btRR.setBorder(null);
        btRR.setBorderPainted(false);
        btRR.setFocusPainted(false);
        btRR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRRActionPerformed(evt);
            }
        });
        pnTaiSan.add(btRR);

        jPanel4.add(pnTaiSan, java.awt.BorderLayout.CENTER);

        lbTop1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbTop1.setText("Thuật toán");
        jPanel6.add(lbTop1);

        jPanel4.add(jPanel6, java.awt.BorderLayout.NORTH);

        add(jPanel4);
    }// </editor-fold>//GEN-END:initComponents

    private void btFCFSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFCFSActionPerformed
        addPanel(new PnTTFCFS(), btFCFS);
    }//GEN-LAST:event_btFCFSActionPerformed

    private void btSJFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSJFActionPerformed
        // TODO add your handling code here:
        addPanel(new PnTTSJF(), btSJF);
    }//GEN-LAST:event_btSJFActionPerformed

    private void btRRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRRActionPerformed
        // TODO add your handling code here:
        addPanel(new PnTTRR(), btRR);
    }//GEN-LAST:event_btRRActionPerformed
     public void addPanel(JPanel pn ,JButton bt) {
        pnCenter.removeAll();
        pnCenter.add(pn, BorderLayout.CENTER);
       
        if(btRecently!=null && btRecently!=bt){
            btRecently.setForeground(Color.BLACK);
            btRecently=bt;
             btRecently.setForeground(Color.RED);
        }else if(btRecently==null){
             btRecently=bt;
             btRecently.setForeground(Color.RED);
        }
        
        pnCenter.revalidate();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btFCFS;
    private javax.swing.JButton btRR;
    private javax.swing.JButton btSJF;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel lbTop1;
    private javax.swing.JPanel pnTaiSan;
    // End of variables declaration//GEN-END:variables
}
