/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view1;

import bean.Proc;
import controller.ControllerFCFS;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.JSplitPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import library.LibraryDimension;

/**
 *
 * @author MinhHuyHo
 */
public class PnTTFCFS extends javax.swing.JPanel implements ActionListener {

    private DefaultTableModel modelTT, modelKQ;
    private int crow;
    private int rowCount = 0;
    private controller.ControllerFCFS controller;
    private ArrayList<Proc> listItemTT;
    private ArrayList<Proc> listItemKQ;
    private int ktModel = 0;
    private Vector v;

    public PnTTFCFS() {
        initComponents();
        v = new Vector();

        crow = -1;
        rowCount = tbFCFSKQ.getSelectedRowCount();
        controller = new ControllerFCFS(taKQ,tfSumTime,tfAverage);
        listItemTT = new ArrayList<Proc>();
        listItemKQ = new ArrayList<>();
        //set split pane
        JSplitPane sp = new JSplitPane(JSplitPane.HORIZONTAL_SPLIT, pnCatLeft, pnCatRight);
        sp.setOneTouchExpandable(true);
        add(sp);
        pnCatLeft.setMinimumSize(new Dimension(LibraryDimension.PANEL_LEFT_WIDTH, pnCatLeft.getSize().height));
        modelTT = new DefaultTableModel() {

            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }

            @Override
            public Class<?> getColumnClass(int columnIndex) {
                if (columnIndex == 0) {
                    return Integer.class;
                }
                return Double.class;

            }

        };
        modelKQ = new DefaultTableModel() {

            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }

            @Override
            public Class<?> getColumnClass(int columnIndex) {
                if (columnIndex == 0) {
                    return Integer.class;
                }
                return Double.class;
            }

        };

        loadTable(listItemTT, 0, modelTT, tbFCFSTT);
        loadTable(listItemKQ, 1, modelKQ, tbFCFSKQ);

        //
        btFCFSThem.addActionListener(this);
        btFCFSSua.addActionListener(this);
        btFCFSXoa.addActionListener(this);
        btFCFSNhapLai.addActionListener(this);
        btFCFSKQ.addActionListener(this);

        ((JComponent) tbFCFSKQ.getDefaultRenderer(Boolean.class)).setOpaque(true);
        ((JComponent) tbFCFSTT.getDefaultRenderer(Boolean.class)).setOpaque(true);

    }

    public void loadTable(ArrayList<Proc> listItem, int ckModel, DefaultTableModel model, JTable tb) {
        controller.loadTable(tb, model, listItem, ckModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnCatLeft = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btFCFSThem = new javax.swing.JButton();
        btFCFSSua = new javax.swing.JButton();
        btFCFSNhapLai = new javax.swing.JButton();
        btFCFSXoa = new javax.swing.JButton();
        tfFCFSId = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfFCFSTimeRun = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbFCFSTT = new javax.swing.JTable();
        btFCFSKQ = new javax.swing.JButton();
        pnCatRight = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbFCFSKQ = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfSumTime = new javax.swing.JTextField();
        tfAverage = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        taKQ = new javax.swing.JTextArea();

        setLayout(new java.awt.BorderLayout());

        pnCatLeft.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Form chức năng", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 102, 0))); // NOI18N
        pnCatLeft.setLayout(new java.awt.BorderLayout());

        jLabel1.setText("ID:");

        btFCFSThem.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btFCFSThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add-icon.gif"))); // NOI18N
        btFCFSThem.setText("Thêm");
        jPanel3.add(btFCFSThem);

        btFCFSSua.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btFCFSSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit-icon.gif"))); // NOI18N
        btFCFSSua.setText("Sửa");
        btFCFSSua.setPreferredSize(new java.awt.Dimension(85, 25));
        jPanel3.add(btFCFSSua);

        btFCFSNhapLai.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btFCFSNhapLai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit.gif"))); // NOI18N
        btFCFSNhapLai.setText("Nhập lại");
        btFCFSNhapLai.setPreferredSize(new java.awt.Dimension(95, 25));
        btFCFSNhapLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFCFSNhapLaiActionPerformed(evt);
            }
        });
        jPanel3.add(btFCFSNhapLai);

        btFCFSXoa.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btFCFSXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/del.gif"))); // NOI18N
        btFCFSXoa.setText("Xóa");
        btFCFSXoa.setPreferredSize(new java.awt.Dimension(85, 25));
        jPanel3.add(btFCFSXoa);

        tfFCFSId.setEnabled(false);
        tfFCFSId.setPreferredSize(new java.awt.Dimension(6, 32));
        tfFCFSId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfFCFSIdActionPerformed(evt);
            }
        });

        jLabel5.setText("Thời gian thực hiện:");

        tfFCFSTimeRun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfFCFSTimeRunActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfFCFSTimeRun, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfFCFSId, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfFCFSId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfFCFSTimeRun, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 181, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );

        pnCatLeft.add(jPanel1, java.awt.BorderLayout.CENTER);

        tbFCFSTT.setAutoCreateRowSorter(true);
        tbFCFSTT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        tbFCFSTT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbFCFSTTMousePressed(evt);
            }
        });
        tbFCFSTT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbFCFSTTKeyReleased(evt);
            }
        });
        jScrollPane3.setViewportView(tbFCFSTT);

        btFCFSKQ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/msg-ok.gif"))); // NOI18N
        btFCFSKQ.setText("Kết quả");
        btFCFSKQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFCFSKQActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btFCFSKQ)
                        .addGap(195, 195, 195))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btFCFSKQ))
        );

        pnCatLeft.add(jPanel2, java.awt.BorderLayout.SOUTH);

        add(pnCatLeft, java.awt.BorderLayout.LINE_START);

        pnCatRight.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Kết quả", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 102, 0))); // NOI18N

        tbFCFSKQ.setAutoCreateRowSorter(true);
        tbFCFSKQ.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        tbFCFSKQ.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbFCFSKQ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbFCFSKQMousePressed(evt);
            }
        });
        tbFCFSKQ.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbFCFSKQKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tbFCFSKQ);
        if (tbFCFSKQ.getColumnModel().getColumnCount() > 0) {
            tbFCFSKQ.getColumnModel().getColumn(1).setResizable(false);
        }

        jLabel2.setText("Tổng thời gian chờ:");

        jLabel3.setText("Thời gian chờ trung bình:");

        tfSumTime.setEnabled(false);
        tfSumTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSumTimeActionPerformed(evt);
            }
        });

        tfAverage.setEnabled(false);
        tfAverage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAverageActionPerformed(evt);
            }
        });

        taKQ.setColumns(20);
        taKQ.setRows(5);
        jScrollPane2.setViewportView(taKQ);
        taKQ.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout pnCatRightLayout = new javax.swing.GroupLayout(pnCatRight);
        pnCatRight.setLayout(pnCatRightLayout);
        pnCatRightLayout.setHorizontalGroup(
            pnCatRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCatRightLayout.createSequentialGroup()
                .addGroup(pnCatRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnCatRightLayout.createSequentialGroup()
                        .addGroup(pnCatRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnCatRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfAverage, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfSumTime, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnCatRightLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnCatRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane2))))
                .addContainerGap())
        );

        pnCatRightLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {tfAverage, tfSumTime});

        pnCatRightLayout.setVerticalGroup(
            pnCatRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCatRightLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 171, Short.MAX_VALUE)
                .addGroup(pnCatRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfSumTime, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnCatRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfAverage, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(19, 19, 19))
        );

        pnCatRightLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {tfAverage, tfSumTime});

        add(pnCatRight, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void tbFCFSKQKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbFCFSKQKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_tbFCFSKQKeyReleased

    private void tbFCFSKQMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbFCFSKQMousePressed
        // TODO add your handling code here:

    }//GEN-LAST:event_tbFCFSKQMousePressed

    private void btFCFSNhapLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFCFSNhapLaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btFCFSNhapLaiActionPerformed

    private void tfFCFSTimeRunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfFCFSTimeRunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfFCFSTimeRunActionPerformed

    private void tfFCFSIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfFCFSIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfFCFSIdActionPerformed

    private void btFCFSKQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFCFSKQActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btFCFSKQActionPerformed

    private void tbFCFSTTKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbFCFSTTKeyReleased
        // TODO add your handling code here:
        setForm();
    }//GEN-LAST:event_tbFCFSTTKeyReleased

    private void tbFCFSTTMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbFCFSTTMousePressed
        // TODO add your handling code here:
        setForm();
    }//GEN-LAST:event_tbFCFSTTMousePressed

    private void tfSumTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSumTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSumTimeActionPerformed

    private void tfAverageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAverageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfAverageActionPerformed
    public void setForm() {
        crow = tbFCFSTT.getSelectedRow();
        tfFCFSId.setText(String.valueOf(tbFCFSTT.getValueAt(crow, 0)));
        tfFCFSTimeRun.setText(String.valueOf(tbFCFSTT.getValueAt(crow, 1)));
    }

    public void resetForm() {
        tfFCFSId.setText("");
        tfFCFSTimeRun.setText("");
        tbFCFSTT.clearSelection();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btFCFSKQ;
    private javax.swing.JButton btFCFSNhapLai;
    private javax.swing.JButton btFCFSSua;
    private javax.swing.JButton btFCFSThem;
    private javax.swing.JButton btFCFSXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel pnCatLeft;
    private javax.swing.JPanel pnCatRight;
    private javax.swing.JTextArea taKQ;
    private javax.swing.JTable tbFCFSKQ;
    private javax.swing.JTable tbFCFSTT;
    private javax.swing.JTextField tfAverage;
    private javax.swing.JTextField tfFCFSId;
    private javax.swing.JTextField tfFCFSTimeRun;
    private javax.swing.JTextField tfSumTime;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        if (e.getSource() == btFCFSThem) {

            if ("".equals(tfFCFSTimeRun.getText())) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập vào thời gian thực hiện");

            } else if (ckNumber(tfFCFSTimeRun.getText()) == 1) {

                ArrayList<Proc> alFCFS = controller.getListTableTT(tbFCFSTT);
                Proc fcfs = new Proc(alFCFS.size() + 1, Double.parseDouble(tfFCFSTimeRun.getText()));
                alFCFS.add(fcfs);
                loadTable(alFCFS, 0, modelTT, tbFCFSTT);
                resetForm();
            }

        }
        if (e.getSource() == btFCFSSua) {
            if ("".equals(tfFCFSTimeRun.getText()) && "".equals(tfFCFSId.getText())) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập vào thời gian thực hiện");

            } else {
                crow = tbFCFSTT.getSelectedRow();
                if (crow < 0) {
                    JOptionPane.showMessageDialog(this, "Vui lòng chọn để sửa");
                    return;
                } else {

                    Proc fcfs = new Proc(Integer.parseInt(tfFCFSId.getText()), Double.parseDouble(tfFCFSTimeRun.getText()));
                    ArrayList<Proc> alFCFS = controller.editFCFSTT(fcfs, tbFCFSTT);
                    loadTable(alFCFS, 0, modelTT, tbFCFSTT);
                    tbFCFSTT.setRowSelectionInterval(crow, crow);
                    resetForm();
                }
            }
        }
        if (e.getSource() == btFCFSNhapLai) {
            resetForm();
        }
        if (e.getSource() == btFCFSXoa) {
            if ("".equals(tfFCFSTimeRun.getText()) && "".equals(tfFCFSId.getText())) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập vào thời gian thực hiện");

            } else {
                crow = tbFCFSTT.getSelectedRow();
                if (crow < 0) {
                    JOptionPane.showMessageDialog(this, "Vui lòng chọn để sửa");
                    return;
                } else {

                    Proc fcfs = new Proc(Integer.parseInt(tfFCFSId.getText()), Double.parseDouble(tfFCFSTimeRun.getText()));
                    ArrayList<Proc> alFCFS = controller.deleteFCFSTT(fcfs, tbFCFSTT);
                    loadTable(alFCFS, 0, modelTT, tbFCFSTT);
                    tbFCFSTT.setRowSelectionInterval(crow, crow);
                    resetForm();
                }
            }
        }
        if (e.getSource() == btFCFSKQ) {
            int countRows = tbFCFSTT.getRowCount();
            if (countRows <= 0) {
                JOptionPane.showMessageDialog(this, "Chưa có tiến trình nào");
            } else {
                ArrayList<Proc> alFCFS = controller.ketQua(tbFCFSTT);
                loadTable(alFCFS, 1, modelKQ, tbFCFSKQ);
                
            }
        }

    }

   

    public int ckNumber(String num) {
        int ck=1;
        try {
            Double.parseDouble(num);
        } catch (NumberFormatException ex) {
            ck=0;
            JOptionPane.showMessageDialog(this, "Vui lòng nhập vào số");
            
        }
        return ck;
    }

}
